name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Get runner IP address
      run: |
        curl -s https://api.ipify.org > runner-ip.txt
    - name: Upload runner IP address
      uses: actions/upload-artifact@v3
      with:
        name: runner-ip
        path: runner-ip.txt
    - name: Checkout code
      uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.9.0]
    needs: checkout
    steps:
    - name: Download runner IP address
      uses: actions/download-artifact@v3
      with:
        name: runner-ip
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install # Ensure package-lock.json is in the root of the repository
    - name: Build project
      run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download runner IP address
      uses: actions/download-artifact@v3
      with:
        name: runner-ip
    - name: Deploy Application
      run: npm start
