name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Checkout Job
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List directory contents
      run: |
        echo "Current directory:"
        pwd
        echo "Contents:"
        ls -R

  # Build Job
  build:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '19.9.0'
    - name: Change to app directory
      run: cd nodejs-app
    - name: Install dependencies
      run: |
        cd nodejs-app
        npm install
    - name: Build project
      run: |
        cd nodejs-app
        npm run build --if-present
